[package]
name = "tbd-memory"
version = "0.1.0"
authors = ["Florian Gilcher <florian.gilcher@asquera.de>"]
edition = "2018"

[dependencies]
tbd-core = { path = "../tbd-core" }
futures-preview = "0.3.0-alpha.6"
